### ISSUE TITLE
Clearing leafiny/var cache manually breaks site

### ISSUE THREAD

**Issue by AbsenceGameDev** [leafiny/cms#2]
So as the title say: clearing the leafiny/var/cache directory broke the deployed site.
After clearing the directory mentioned above, the website never loads but gets redirected indefinitely until I get 'ERR_TOO_MANY_REDIRECTS'

Restoring the files is not possible as it was cleared using filezilla (which has no undo delete option).

**Comment by AbsenceGameDev** [comment]
Not sure what broke initially, but I re-uploaded my site completely to the server and it runs as expected now

**Comment by magentix** [comment]
Hi,

A redirect loop often appears when **https** is redirect to **http** by Leafiny and **http** to **https** by the web server (or the opposite).

In the config file in the **etc** directory, check the **is_secure** option:

```
    'page' => [
        'default' => [
            'is_secure' => 0,
            'locale'    => 'fr_FR.utf8',
            'fpc'       => 0,
        ],
    ],
```

If your website is under SSL, the **is_secure** option must be set to 1. When the cache is flushed, this config is updated (that's why you got the error after deleting the **var/cache** folder).

**Comment by AbsenceGameDev** [comment]
Hey, 
Yes I believe you are correct. I had been using the 'dev' config when I had deployed as initially the website wasn't under SSL, but shortly after deploying the site I decided to set up SSL and forgot that I had the dev config selected. 
And when I reuploaded the website to the server, I selected the 'default' config instead, which also would explain why it started working again after that.

Thanks you for your reply, gave me some more insight into the problem
